# Generated by Django 4.2.4 on 2023-08-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('framework', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=100)),
            ],
        ),
    ]
