# Generated by Django 4.2.4 on 2023-08-21 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0005_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='title',
            field=models.TextField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
